### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by RorschachChen** [JunfengGo/SCALE-UP#1]
When creating tiny_bd.npy, the labels loaded is a list of all target label, such as torch.load('bd_labels.pth') saved from BackdoorBox or the same "benign_labels.pth"

**Comment by THUYimingLi** [comment]
> When creating tiny_bd.npy, the labels loaded is a list of all target label, such as torch.load('bd_labels.pth') saved from BackdoorBox or the same "benign_labels.pth"

 Can you describe your question more specifically?
